### PR TITLE
Enable arbitrary contract call support

### PR DESCRIPTION
**Pull request by cryptoriver**
### What
We want to implement arbitrary contract call transaction construction on Flare, the major missing piece is the contract call ABI data encoding part, for that purpose, we introduce a utility method `constructContractCallDataGeneric`. 

Other than that, we updated the handlers of these endpoints to enable producing/carrying contract call data.

* /construction/preprocess
* /construction/metadata
* /construction/parse
* /construction/payloads

 **Note:** For contract call arguments contain tuple type, client will need to encode and pass the ABI data to Rosetta node.

### Test
* Unit tests
* Integration tests - [generic contract call test - explorer](https://coston2-explorer.flare.network/tx/0x3da3c20b05b826dd6b98c6be5c48b4811d3e129471cbd7692e72c8bea7b4a96e/logs)

#### Regression Tests 
* [FLR native currency send test - explorer](https://coston2-explorer.flare.network/tx/0x30bd50540e06127f7ee5001944a44f4400f019c7929eba12dcc4ca77ef0846bd)

### CODE REVIEW

**Review by aljazs-flare — COMMENTED** [review]
The `server/Dockerfile.arm64` and `server/Makefile` only add functionality to run the server on arm. I will not comment on other changes and I am not proficient enough in Golang.

**Comment by cryptoriver** [comment]
> The `server/Dockerfile.arm64` and `server/Makefile` only add functionality to run the server on arm. I will not comment on other changes and I am not proficient enough in Golang.

Hi @aljazs-flare , thank you for your comment! Do you know or could you help invite some golang developers from flare team to help this PR ?

**Comment by aljazs-flare** [comment]
> > The `server/Dockerfile.arm64` and `server/Makefile` only add functionality to run the server on arm. I will not comment on other changes and I am not proficient enough in Golang.
> 
> Hi @aljazs-flare , thank you for your comment! Do you know or could you help invite some golang developers from flare team to help this PR ?

Yeah it was mentioned already on slack a few times. I'll try to get someone on it - can't promise anything though, not really in position to give orders 😅

**Comment by cryptoriver** [comment]
> > > The `server/Dockerfile.arm64` and `server/Makefile` only add functionality to run the server on arm. I will not comment on other changes and I am not proficient enough in Golang.
> > 
> > 
> > Hi @aljazs-flare , thank you for your comment! Do you know or could you help invite some golang developers from flare team to help this PR ?
> 
> Yeah it was mentioned already on slack a few times. I'll try to get someone on it - can't promise anything though, not really in position to give orders 😅

Got it, really appreciate your help! 🙏 Let me know if there's anything I can help.

**Comment by aljazs-flare** [comment]
It would be good tho if you also added the GH workflow that builds the arm64 image and pushes it to ghcr.io and dockerhub (like the x86_64 one).

**Pull request merged**
